#!/bin/bash
#
#PBS -S /bin/bash
#PBS -l select=2:ncpus=24:model=has
#PBS -l walltime=10:00:00
#PBS -N COVIRT_raw_fastqc
#PBS -q covid19
#PBS -m abe
#PBS -j oe

cd $PBS_O_WORKDIR

start=$(date +%s)
echo "start time: $start"
echo "ran on node: "
cat $PBS_NODEFILE

cat samples.txt | parallel -j 12 -u --sshloginfile $PBS_NODEFILE "cd $PWD;./raw_fastqc.sh {} > ./raw_fastqc_stdout/out_{} 2>&1"

end=$(date +%s)
echo "end time: $end"
runtime_s=$(echo $(( end - start )))
echo "total run time(s): $runtime_s"
sec_per_min=60
sec_per_hr=3600
runtime_m=$(echo "scale=2; $runtime_s / $sec_per_min;" | bc)
echo "total run time(m): $runtime_m"
runtime_h=$(echo "scale=2; $runtime_s / $sec_per_hr;" | bc)
echo "total run time(h): $runtime_h"
