#!/bin/bash
#
#PBS -S /bin/bash
#PBS -l select=5:ncpus=24:model=has
#PBS -l walltime=720:00:00
#PBS -N COVIRT_GATK_calls7-9_all
#PBS -q covid19
#PBS -m abe
#PBS -j oe
#PBS -koed

cd $PBS_O_WORKDIR

start=$(date +%s)
echo "start time: $start"
echo "ran on node: "
cat $PBS_NODEFILE

gatk_path=/path/to/anaconda3/envs/COVIRT_GATK/bin
in_dir=/path/to/02-AlignedData
inter_dir=/path/to/GATK_analysis/03-GATKIntermediates
out_dir=/path/to/GATK_analysis/04-GATKOutput

genome_ref=/path/to/genome_files/Homo_sapiens/ensembl_release100
vcf_ref=/path/to/genome_files/Homo_sapiens/ensembl_release100/vcf_files


mkdir $out_dir/all_samples
mkdir $out_dir/GVCF_databases

cat chromosomes_ensembl.txt | parallel -j 3 -k -u --sshloginfile $PBS_NODEFILE "cd $PWD;./GATK_calls7-9.sh {} > ./GATK_calls7-9_stdout/out_{} 2>&1"

end=$(date +%s)
echo "end time: $end"
runtime_s=$(echo $(( end - start )))
echo "total run time(s): $runtime_s"
sec_per_min=60
sec_per_hr=3600
runtime_m=$(echo "scale=2; $runtime_s / $sec_per_min;" | bc)
echo "total run time(m): $runtime_m"
runtime_h=$(echo "scale=2; $runtime_s / $sec_per_hr;" | bc)
echo "total run time(h): $runtime_h"
