#!/bin/bash
#
#PBS -S /bin/bash
#PBS -l select=1:ncpus=24:model=has
#PBS -l walltime=16:00:00
#PBS -N COVIRT_STAR_index_Hsap_RL-151
#PBS -q covid19
#PBS -m abe
#PBS -j oe

cd $PBS_O_WORKDIR

start=$(date +%s)
echo "start time: $start"
echo "ran on node: "
cat $PBS_NODEFILE 

genome_files_dir=/path/to/genome_files/Homo_sapiens/ensembl_release100
STAR_index_dir=/path/to/STAR_Indices

call="STAR --runThreadN 44 \
--runMode genomeGenerate \
--limitGenomeGenerateRAM 105000000000 \
--genomeDir $STAR_index_dir/Homo_sapiens_RL-151 \
--genomeFastaFiles $genome_files_dir/Homo_sapiens.GRCh38.dna.primary_assembly.fa \
--sjdbGTFfile $genome_files_dir/Homo_sapiens.GRCh38.100.gtf \
--sjdbOverhang 150"

echo $call
eval $call

end=$(date +%s)
echo "end time: $end"
runtime_s=$(echo $(( end - start )))
echo "total run time(s): $runtime_s"
sec_per_min=60
sec_per_hr=3600
runtime_m=$(echo "scale=2; $runtime_s / $sec_per_min;" | bc)
echo "total run time(m): $runtime_m"
runtime_h=$(echo "scale=2; $runtime_s / $sec_per_hr;" | bc)
echo "total run time(h): $runtime_h"
